### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by MalikSamiAwan** [xsoulspace/tables_syncer_excel_addin#1]
How can i set it up for windows excel?

**Comment by Arenukvern** [comment]
@MalikSamiAwan 
currently I don't have the readme section, but you can start with side loading for windows
https://learn.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins

**Comment by MalikSamiAwan** [comment]
@Arenukvern Thanks for answering 
But its not working i even tried this method on this sample raw
https://raw.githubusercontent.com/xsoulspace/sheets_manager_excel_addin/develop/manifests/office_manifest.xml

**Comment by MalikSamiAwan** [comment]
Thanks for helping it is resolved
