### ISSUE TITLE
Missing firebase_options.dart file

### ISSUE THREAD

**Issue by MalikSamiAwan** [xsoulspace/tables_syncer_excel_addin#2]
The code is missing this file
import 'package:tables_syncer_excel_addin/firebase_options.dart';

**Comment by Arenukvern** [comment]
@MalikSamiAwan 
hello! Yes, I did it on purpose, to not share credentials from my firebase account. In case if you need to setup this project - you can just setup regular firebase project and run flutterfire configure, and then use this project standalone..

not sure it is the best way, but currently I don't know how to do it better:)

**Comment by MalikSamiAwan** [comment]
ok Thanks
